name: Laravel

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: htawb2d3d
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}

          script: |
            cd /var/www/htawb_version_two
            git pull origin master
            chmod -R 777 storage bootstrap/cache
            php artisan config:clear
            php artisan storage:link
            # php artisan migrate:fresh --seed
            php artisan passport:install
             php artisan migrate
            # composer install
            # composer dump-autoload
            echo 'Deployment successful to digital ocean'
